# Generated by Django 4.2 on 2024-09-08 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_types', to='visas.country')),
            ],
        ),
        migrations.CreateModel(
            name='VisaRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.TextField()),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='visas.visatype')),
            ],
        ),
        migrations.CreateModel(
            name='VisaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_orders', to=settings.AUTH_USER_MODEL)),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visas.visatype')),
            ],
        ),
        migrations.CreateModel(
            name='VisaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200)),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='visas.visatype')),
            ],
        ),
        migrations.CreateModel(
            name='VisaAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Ваш возраст')),
                ('citizenship', models.CharField(max_length=100, verbose_name='Ваше гражданство')),
                ('residence', models.CharField(max_length=255, verbose_name='В какой стране и городе Вы проживаете')),
                ('marital_status', models.CharField(max_length=50, verbose_name='Ваш семейный статус')),
                ('travel_purpose', models.CharField(max_length=100, verbose_name='Цель поездки')),
                ('who_pays', models.CharField(max_length=100, verbose_name='Кто оплачивает Вашу поездку')),
                ('previous_visa', models.CharField(max_length=100, verbose_name='Была ли у Вас ранее туристическая виза')),
                ('previous_trips', models.TextField(help_text='Если да, то уточните в каком статусе и продолжительность поездки', verbose_name='Были ли Вы ранее в этой стране')),
                ('visa_denial', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=3, verbose_name='Отказывали ли Вам когда-либо в визе')),
                ('relatives_in_country', models.TextField(verbose_name='Есть ли родственники или друзья в этой стране')),
                ('occupation', models.CharField(max_length=100, verbose_name='Ваша текущая сфера деятельности')),
                ('work_experience', models.CharField(max_length=100, verbose_name='Срок работы в текущей компании')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Заработная плата (руб/мес)')),
                ('visited_countries', models.TextField(verbose_name='Зарубежные страны, которые вы посетили за последние 5 лет')),
                ('deported', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=3, verbose_name='Были ли Вы депортированы из других стран')),
                ('illegal_stay', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=3, verbose_name='Находились ли Вы когда-либо незаконно на территории другой страны')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Отправлена'), ('processing', 'В работе'), ('done', 'Обработана')], default='active', max_length=20, verbose_name='Статус заявки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='visas.visatype')),
            ],
        ),
    ]
