# Generated by Django 4.2 on 2024-10-21 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visas', '0002_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consultations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачена'), ('manager_assigned', 'Менеджер назначен'), ('time_to_confirm', 'Согласование времени'), ('time_scheduled', 'Время назначено'), ('service_provided', 'Услуга оказана')], default='paid', max_length=20, verbose_name='Статус консультации'),
        ),
        migrations.AddField(
            model_name='visaassessment',
            name='recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендации'),
        ),
        migrations.AddField(
            model_name='visaassessment',
            name='result',
            field=models.TextField(blank=True, null=True, verbose_name='Результат оценки'),
        ),
        migrations.AddField(
            model_name='visaorder',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visaassessment',
            name='status',
            field=models.CharField(choices=[('received', 'Получена'), ('processing', 'В работе'), ('done', 'Готова')], default='received', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='visaorder',
            name='status',
            field=models.CharField(choices=[('paid', 'Оплачен'), ('manager_assigned', 'Менеджер назначен'), ('awaiting_documents', 'Ожидание документов'), ('awaiting_interview', 'Ожидание записи'), ('scheduled', 'Записан на собеседование'), ('approved', 'Виза одобрена'), ('denied', 'Отказ'), ('completed', 'Заявка закрыта')], default='paid', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('document_type', models.CharField(max_length=255, verbose_name='Тип документа')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='visas.visaorder')),
            ],
        ),
    ]
