# Generated by Django 4.2 on 2024-10-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0005_consultation_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultation',
        ),
    ]
