# Generated by Django 4.2 on 2024-11-19 16:08

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0006_delete_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaassessment',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
