# Generated by Django 4.2 on 2024-12-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0007_alter_visaassessment_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название визы')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('consular_fee', models.BooleanField(default=False, verbose_name='Включен ли консульский сбор')),
                ('order_url', models.URLField(blank=True, max_length=300, verbose_name='Ссылка для заказа')),
            ],
            options={
                'verbose_name': 'Визовая карточка',
                'verbose_name_plural': 'Визовые карточки',
            },
        ),
    ]
