# Generated by Django 4.2 on 2024-12-02 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visas', '0008_visacard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visaorder',
            options={'ordering': ['-order_date'], 'verbose_name': 'Заказ на визу', 'verbose_name_plural': 'Заказы на визы'},
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название страны'),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='visas.visaorder', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=300, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='visa_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='visas.visatype', verbose_name='Тип визы'),
        ),
        migrations.AlterField(
            model_name='visadocument',
            name='document_name',
            field=models.CharField(max_length=200, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='visadocument',
            name='visa_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='visas.visatype', verbose_name='Тип визы'),
        ),
        migrations.AlterField(
            model_name='visaorder',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='visaorder',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='visaorder',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='visaorder',
            name='required_documents',
            field=models.ManyToManyField(blank=True, to='visas.visadocument', verbose_name='Требуемые документы'),
        ),
        migrations.AlterField(
            model_name='visaorder',
            name='status',
            field=models.CharField(choices=[('paid', 'Заказ оплачен'), ('manager_assigned', 'Менеджер назначен'), ('awaiting_documents', 'Ожидание документов'), ('awaiting_interview', 'Ожидание записи'), ('scheduled', 'Записан на собеседование'), ('approved', 'Виза одобрена'), ('denied', 'Отказ'), ('completed', 'Заявка закрыта')], default='paid', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='visaorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='visaorder',
            name='visa_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visas.visatype', verbose_name='Тип визы'),
        ),
        migrations.AlterField(
            model_name='visarequirement',
            name='requirement',
            field=models.TextField(verbose_name='Требование'),
        ),
        migrations.AlterField(
            model_name='visarequirement',
            name='visa_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='visas.visatype', verbose_name='Тип визы'),
        ),
        migrations.AlterField(
            model_name='visatype',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_types', to='visas.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='visatype',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='visatype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Тип визы'),
        ),
    ]
