# Generated by Django 4.2 on 2024-12-02 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0010_alter_country_options_alter_documentupload_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanadaVisaCard',
            fields=[
            ],
            options={
                'verbose_name': 'Карточка визы Канады',
                'verbose_name_plural': 'Карточки виз Канады',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('visas.visacard',),
        ),
        migrations.CreateModel(
            name='USAVisaCard',
            fields=[
            ],
            options={
                'verbose_name': 'Карточка визы США',
                'verbose_name_plural': 'Карточки виз США',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('visas.visacard',),
        ),
        migrations.AddField(
            model_name='visacard',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visa_cards', to='visas.country', verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
