# Generated by Django 4.2 on 2024-12-02 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0012_alter_visacard_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visacard',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visas.country', verbose_name='Страна'),
        ),
    ]
