# Generated by Django 4.2 on 2024-12-02 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0015_delete_canadavisacard_delete_usavisacard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visacard',
            name='order_url',
        ),
    ]
