# Generated by Django 4.2 on 2024-12-02 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0016_remove_visacard_order_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaorder',
            name='visa_type',
        ),
        migrations.AddField(
            model_name='visaorder',
            name='visa_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visas.visacard', verbose_name='Виза'),
        ),
    ]
