# Generated by Django 4.2 on 2024-10-22 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Unknown', max_length=255, verbose_name='ФИО')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема консультации')),
                ('date', models.DateField(verbose_name='Дата консультации')),
                ('time', models.TimeField(verbose_name='Время консультации')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('status', models.CharField(choices=[('paid', 'Оплачена'), ('manager_assigned', 'Менеджер назначен'), ('time_to_confirm', 'Согласование времени'), ('time_scheduled', 'Время назначено'), ('service_provided', 'Услуга оказана')], default='paid', max_length=20, verbose_name='Статус консультации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_consultations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
