# Generated by Django 4.2 on 2024-10-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='zoom_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на Zoom комнату'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='ФИО'),
        ),
    ]
