# Generated by Django 4.2 on 2024-10-22 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0004_availableslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableslot',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Занято'),
        ),
        migrations.AlterField(
            model_name='availableslot',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
    ]
