# Generated by Django 4.2 on 2024-12-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_alter_availableslot_is_booked_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availableslot',
            options={'verbose_name': 'Доступный слот', 'verbose_name_plural': 'Доступные слоты'},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Заказ на консультацию', 'verbose_name_plural': 'Заказы на консультации'},
        ),
    ]
