"""
Django settings for Visa4u project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!npo1gn8cu774!5uv3ar(t^43fx2eilh-67w=pomu()uird2o_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'apps.visas',
    'apps.accounts',
    'apps.consultations',
    'channels',
    'apps.chat',
]

ASGI_APPLICATION = 'Visa4u.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],  # Адрес сервера Redis
        },
    },
}

JAZZMIN_SETTINGS = {
    "site_title": "Управление визовыми заявками",
    "site_header": "Админка ClickCheck",
    "welcome_sign": "Добро пожаловать в административную панель",
    "site_brand": "ClickCheck Project",
    # "site_logo": "your_logo.png", # добавить сюда лого
    "show_ui_builder": True,

    # Настройка меню с категориями
    "topmenu_links": [
        # Группа "Visas"
        {"name": "Visas", "icon": "fas fa-passport", "models": [
            {"name": "Countries", "model": "visas.country"},
            {"name": "Visa Types", "model": "visas.visatype"},
            {"name": "Visa Requirements", "model": "visas.visarequirement"},
            {"name": "Visa Documents", "model": "visas.visadocument"},
            {"name": "Visa Assessments", "model": "visas.visaassessment"},
            {"name": "Visa Orders", "model": "visas.visaorder"},
            {"name": "Document Uploads", "model": "visas.documentupload"},
            {"name": "FAQs", "model": "visas.faq"},
        ]},

        # Группа "Consultations"
        {"name": "Consultations", "icon": "fas fa-calendar-alt", "models": [
            {"name": "Available Slots", "model": "consultations.availableslot"},
            {"name": "Consultations", "model": "consultations.consultation"},
        ]},

        # Группа "Chat"
        {"name": "Chat", "icon": "fas fa-comments", "models": [
            {"name": "Messages", "model": "chat.message"},
        ]},
    ],

    # Настройки иконок для моделей
    "icons": {
        "visas.Country": "fas fa-flag",
        "visas.VisaType": "fas fa-passport",
        "visas.VisaRequirement": "fas fa-file-alt",
        "visas.VisaDocument": "fas fa-folder",
        "visas.VisaAssessment": "fas fa-check-circle",
        "visas.VisaOrder": "fas fa-file-signature",
        "visas.FAQ": "fas fa-question-circle",
        "visas.DocumentUpload": "fas fa-upload",
        "consultations.AvailableSlot": "fas fa-calendar-check",
        "consultations.Consultation": "fas fa-user-clock",
        "chat.Message": "fas fa-comments",
    },
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Visa4u.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Visa4u.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки для перенаправлений после аутентификации
LOGIN_REDIRECT_URL = 'dashboard'  # Переадресация на личный кабинет после входа
LOGOUT_REDIRECT_URL = '/'         # Переадресация на главную страницу после выхода


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'db.prokhorova@gmail.com'  # Почта, с которой будут отправляться письма
EMAIL_HOST_PASSWORD = 'flfg mmyb nziz xwly'  # Пароль или пароль приложения для Gmail
DEFAULT_FROM_EMAIL = 'noreply@clickcheck.com'  # Это будет указано как "От кого" в письме
