# Generated by Django 4.2 on 2024-11-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_sender_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
